services:
  elasticsearch:  # Database, core of the ELK stack
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4  # most recent on 2025-10-02
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # désactive la sécurité pour simplifier le projet de cours
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - medical_net

  kibana: # User interface
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - medical_net

  logstash: # Receive new medical data and feed ElasticSeach database
    image: docker.elastic.co/logstash/logstash:9.1.4
    container_name: logstash
    ports:
      - "5044:5044"
      #- "5001:5001"  # TCP port for new data acquisition
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - medical_net

  python: # Generate new medical data
    image: python:3.9-slim
    container_name: data-generator
    command: python3 /scripts/generate_data.py
    volumes:
      - ./scripts:/scripts  # Monte ton répertoire contenant le script Python
    depends_on:
      - logstash
    networks:
      - medical_net

networks:
  medical_net:
